---
# handlers file for base
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
    enabled: true
  become: true

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true

- name: Enable Gstreamer
  ansible.builtin.service:
    name: gstreamer
    state: restarted
    enabled: true
