---
- name: Common | sshd.yml | Copy warning banners over
  become: true
  ansible.builtin.copy:
    src: files/issue.net
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  with_items:
    - "/etc/issue.net"
    - "/etc/issue"
  notify: Restart sshd

- name: Common | sshd.yml | Copy sshd_config template over
  ansible.builtin.template:
    src: templates/sshd_conf.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  become: true
  notify: Restart sshd

# - name: Base | sshd | Add Ansible server public key
#   ansible.posix.authorized_key:
#     user: "{{ system_username }}"
#     state: present
#     key: "{{ base_ssh_ansible_key }}"
#   notify: Restart sshd
